/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/ray-automl/apis/automl/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrainers implements TrainerInterface
type FakeTrainers struct {
	Fake *FakeAutomlV1
	ns   string
}

var trainersResource = corev1.SchemeGroupVersion.WithResource("trainers")

var trainersKind = corev1.SchemeGroupVersion.WithKind("Trainer")

// Get takes name of the trainer, and returns the corresponding trainer object, and an error if there is any.
func (c *FakeTrainers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Trainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trainersResource, c.ns, name), &v1.Trainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Trainer), err
}

// List takes label and field selectors, and returns the list of Trainers that match those selectors.
func (c *FakeTrainers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TrainerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trainersResource, trainersKind, c.ns, opts), &v1.TrainerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.TrainerList{ListMeta: obj.(*v1.TrainerList).ListMeta}
	for _, item := range obj.(*v1.TrainerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trainers.
func (c *FakeTrainers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trainersResource, c.ns, opts))

}

// Create takes the representation of a trainer and creates it.  Returns the server's representation of the trainer, and an error, if there is any.
func (c *FakeTrainers) Create(ctx context.Context, trainer *v1.Trainer, opts metav1.CreateOptions) (result *v1.Trainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trainersResource, c.ns, trainer), &v1.Trainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Trainer), err
}

// Update takes the representation of a trainer and updates it. Returns the server's representation of the trainer, and an error, if there is any.
func (c *FakeTrainers) Update(ctx context.Context, trainer *v1.Trainer, opts metav1.UpdateOptions) (result *v1.Trainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trainersResource, c.ns, trainer), &v1.Trainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Trainer), err
}

// Delete takes name of the trainer and deletes it. Returns an error if one occurs.
func (c *FakeTrainers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(trainersResource, c.ns, name, opts), &v1.Trainer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrainers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trainersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.TrainerList{})
	return err
}

// Patch applies the patch and returns the patched trainer.
func (c *FakeTrainers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Trainer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trainersResource, c.ns, name, pt, data, subresources...), &v1.Trainer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Trainer), err
}
