/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	automlv1 "github.com/ray-automl/apis/automl/v1"
	versioned "github.com/ray-automl/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ray-automl/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/ray-automl/pkg/client/listers/automl/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TrainerInformer provides access to a shared informer and lister for
// Trainers.
type TrainerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.TrainerLister
}

type trainerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTrainerInformer constructs a new informer for Trainer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTrainerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTrainerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTrainerInformer constructs a new informer for Trainer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTrainerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutomlV1().Trainers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutomlV1().Trainers(namespace).Watch(context.TODO(), options)
			},
		},
		&automlv1.Trainer{},
		resyncPeriod,
		indexers,
	)
}

func (f *trainerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTrainerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *trainerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&automlv1.Trainer{}, f.defaultInformer)
}

func (f *trainerInformer) Lister() v1.TrainerLister {
	return v1.NewTrainerLister(f.Informer().GetIndexer())
}
